timeout: 300
outputs:
  - command: dds
    head: 6
    tail: 29
    img_paths:
      - img/dds-help-1.svg
  - command: dds --help
    head: 6
    tail: 29
    img_paths: 
      - img/dds-help-2.svg
  - command: dds auth
    head: 6
    tail: 19
    img_paths:
      - img/dds-auth.svg