timeout: 300
outputs:
  - command: python --version
    img_paths:
      - img/python-version.svg
  - command: python3 --version
    img_paths:
      - img/python3-version.svg
  - command: echo 'Successfully installed pip-22.3.1'
    fake_command: python3 -m pip install --upgrade pip
    img_paths:
      - img/pip-upgrade.svg
  - command: dds --version
    tail: 1
    img_paths:
      - img/dds-version.svg
  - command: dds
    head: 6
    tail: 29
    img_paths:
      - img/dds-help-1.svg
  - command: dds --help
    head: 6
    tail: 29
    img_paths:
      - img/dds-help-2.svg
  - command: dds auth
    tail: 19
    img_paths:
      - img/dds-auth.svg
  - command: |
      echo "INFO     Attempting to create the session token"
      echo "DDS username:"
      echo "DDS password:"
      echo "INFO     Please enter the one-time authentication code sent to your email address (leave empty to exit):"                                                                
      echo "Authentication one-time code:"
    fake_command: dds auth login
    img_paths:
      - img/dds-auth-login.svg
  - command: dds user
    tail: 18
    img_paths:
      - img/dds-user.svg
  - snippet: |
      Current user: <username>
      INFO    Username:          <username>
              Role:              <role> e.g. Researcher
              Name:              <First name> <Last name>
              Primary Email:     <someemail>@<somedomain>.com
              Associated Emails: <someemail>@<somedomain>.com
    snippet_syntax: Python
    use_pty: true
    img_paths:
      - img/dds-user-info.svg
  - command: dds project
    tail: 16
    img_paths:
      - img/dds-project.svg
  - command: dds data
    tail: 15
    img_paths:
      - img/dds-data.svg
